name: CI

on:
  push:
    branches:
    - master
    - feat/**
    - fix/**
  repository_dispatch:
    types:
    - automated-upgrade-generated

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get supported Deno runtime version number
      id: supported-deno-version
      uses: sergeysova/jq-action@v2
      with:
        cmd: jq -r .deno deno_versions.json

    - name: Install supported Deno runtime version
      run: curl -fsSL https://deno.land/x/install/install.sh | sh -s v${{steps.supported-deno-version.outputs.value}}

    - name: Lint
      run: make lint

    - name: Check formatting
      run: make format-check

    - name: Unit tests
      run: make test

    - name: End-to-end tests
      run: make e2e

  notify-failure:
    runs-on: ubuntu-latest
    needs: build
    if: ${{github.event_name == "automated-upgrade-generated" && needs.build.result == "failure"}}
    steps:
      - name: Dispatch automated-upgrade-build-failed repository event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.UPGRADE_TOKEN}}
          event-type: automated-upgrade-build-failed

