name: CI

on:
  push:
    branches:
    - master
    - feat/**
    - fix/**
  workflow_dispatch:
    inputs:
      pull-request-url:
        required: true
        description: URL of the associated pull request, passed in from the upgrade workflow
      pull-request-number:
        required: true
        description: Number of the associated pull request, passed in from the upgrade workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install supported Deno version
      run: curl -fsSL https://deno.land/x/install/install.sh | sh -s v$(cat .deno_version)

    - name: Lint
      run: make lint

    - name: Check formatting
      run: make format-check

    - name: Unit tests
      run: make test

    - name: End-to-end tests
      run: make e2e

  notify-upgrade:
    runs-on: ubuntu-latest
    needs: build
    if: ${{startsWith(github.ref, 'refs/heads/upgrade')}}
    steps:
      - name: Invoke post-upgrade workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Post-upgrade
          repo: reno-router/reno
          token: ${{ secrets.UPGRADE_TOKEN }}
          inputs: |
            {
              "success": ${{needs.build.result == 'success'}},
              "pull-request-url": "${{github.event.inputs.pull-request-url}}"
              "pull-request-number": ${{github.event.inputs.pull-request-number}}
            }
