name: CI

on:
  push:
    branches:
      - master
      - feat/**
      - fix/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get supported Deno runtime version number
      id: deno-version
      uses: sergeysova/jq-action@v2
      with:
        cmd: jq -r .deno deno_versions.json

    - name: Install supported Deno runtime version
      run: curl -fsSL https://deno.land/x/install/install.sh | sh -s v${{ steps.deno-version.outputs.value }}

    - name: Lint
      run: make lint

    - name: Check formatting
      run: make format-check

    - name: Unit tests
      run: make test

    - name: End-to-end tests
      run: make e2e
