name: Upgrade Deno runtime and std versions

on:
  push:
    branches:
      - feat/automated-upgrade

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      supported-runtime: ${{steps.supported-deno-version.outputs.value}}
      supported-std: ${{steps.supported-std-version.outputs.value}}"
      latest-runtime: ${{steps.latest-deno-version.outputs.release}}
      latest-std: ${{steps.latest-std-version.outputs.release}}"
    steps:
    - uses: actions/checkout@v2

    - name: Get supported Deno runtime version number
      id: supported-deno-version
      uses: sergeysova/jq-action@v2
      with:
        cmd: jq -r .deno deno_versions.json

    - name: Get supported std version number
      id: supported-std-version
      uses: sergeysova/jq-action@v2
      with:
        cmd: jq -r .std deno_versions.json

    - name: Get latest Deno runtime release
      id: latest-deno-version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: denoland
        repo: deno
        excludes: prerelease, draft

    - name: Get latest std release
      id: latest-std-version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: denoland
        repo: deno_std
        excludes: prerelease, draft

  determine-upgrade:
    runs-on: ubuntu-latest
    needs: get-versions
    steps:
      - name: Debug
        run: |
          echo ${{needs.get-versions.outputs.supported-runtime}} ${{needs.get-versions.outputs.supported-std}} ${{needs.get-versions.outputs.latest-runtime}} ${{needs.get-versions.outputs.latest-std}}